# Setup
title: 写在边上
tagline: 'Never left without saying goodbye.'
description: "Astrian's Markdown blog."
url: http://mdblog.astrianfm.com
future: false
timezone: Asia/Shanghai

paginate: 5
paginate_path: "page:num"

author:
  name: 'Astrian'
  email: mingriqd@gmail.com

copyright: "版权所有 © 2015 Astrian &middot; 未经书面许可，不可复制本博客任何内容。"
